### ISSUE TITLE
`vocab.tar.gz` not found

### ISSUE THREAD

**Issue by vidhiJain** [amazon-research/embert#1]
Hi, thanks a lot for sharing the code for EmBert! I am trying to generate the vocabulary for the model by the following command on the README:
```
allennlp build-vocab training_configs/embert/embert_oscar.jsonnet storage/models/embert/vocab.tar.gz --include-package grolp
```
But I receive the following error.
```
FileNotFoundError: file storage/models/embert/vocab.tar.gz not found
```
`vocab.tar.gz` seems important to train the model. Kindly make this file available or advise on where to find it.

**Comment by aleSuglia** [comment]
Hi @vidhiJain,

First of all, apologies for the delay in answering this. Thanks for catching this mismatch. The config file you specified is already assuming you have the `vocab.tar.gz`. You can try deleting the following:
```
"vocabulary": {
        "type": "from_files",
        "directory": "storage/models/embert/vocab.tar.gz"
    }
 ```
and the AllenNLP command should create it automatically for you by reading all the instances generated by the dataset reader. We will make sure to update this and we will also upload the `vocab.tar.gz` soon.

Thanks a lot for your interest in our project. Let us know if you have any issues!

Alessandro

**Comment by siifish** [comment]
Hi, thanks a lot for solving this ploblem before. But there is another ploblem when running this command. Is `vocab.tar.gz` uploaded? That will make it easier. Thanks!

**Comment by aleSuglia** [comment]
Hi @siifish, you can create the vocabulary using the following command as described in the README:

```
allennlp build-vocab training_configs/embert/embert_oscar.jsonnet storage/models/embert/vocab.tar.gz --include-package grolp
```

**Comment by siifish** [comment]
Thanks! But this is another error happened when running this command, it's in [this](https://github.com/amazon-science/embert/issues/2) issue.
